// AUTO-GENERATED

#ifndef _GI_GLIB__CONSTANTS_HPP_
#define _GI_GLIB__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace GLib {

GI_MODULE_INLINE const gint ANALYZER_ANALYZING_ = G_ANALYZER_ANALYZING;

GI_MODULE_INLINE const gint ASCII_DTOSTR_BUF_SIZE_ = G_ASCII_DTOSTR_BUF_SIZE;

GI_MODULE_INLINE const gint ATOMIC_REF_COUNT_INIT_ = G_ATOMIC_REF_COUNT_INIT;

GI_MODULE_INLINE const gint BIG_ENDIAN_ = G_BIG_ENDIAN;

GI_MODULE_INLINE const gchar CSET_A_2_Z_[] = G_CSET_A_2_Z;

GI_MODULE_INLINE const gchar CSET_DIGITS_[] = G_CSET_DIGITS;

GI_MODULE_INLINE const gchar CSET_a_2_z[] = G_CSET_a_2_z;

GI_MODULE_INLINE const gint DATALIST_FLAGS_MASK_ = G_DATALIST_FLAGS_MASK;

GI_MODULE_INLINE const gint DATE_BAD_DAY_ = G_DATE_BAD_DAY;

GI_MODULE_INLINE const gint DATE_BAD_JULIAN_ = G_DATE_BAD_JULIAN;

GI_MODULE_INLINE const gint DATE_BAD_YEAR_ = G_DATE_BAD_YEAR;

GI_MODULE_INLINE const gint DIR_SEPARATOR_ = G_DIR_SEPARATOR;

GI_MODULE_INLINE const gchar DIR_SEPARATOR_S_[] = G_DIR_SEPARATOR_S;

GI_MODULE_INLINE const gdouble E_ = G_E;

GI_MODULE_INLINE const gchar GINT16_FORMAT_[] = G_GINT16_FORMAT;

GI_MODULE_INLINE const gchar GINT16_MODIFIER_[] = G_GINT16_MODIFIER;

GI_MODULE_INLINE const gchar GINT32_FORMAT_[] = G_GINT32_FORMAT;

GI_MODULE_INLINE const gchar GINT32_MODIFIER_[] = G_GINT32_MODIFIER;

GI_MODULE_INLINE const gchar GINT64_FORMAT_[] = G_GINT64_FORMAT;

GI_MODULE_INLINE const gchar GINT64_MODIFIER_[] = G_GINT64_MODIFIER;

GI_MODULE_INLINE const gchar GINTPTR_FORMAT_[] = G_GINTPTR_FORMAT;

GI_MODULE_INLINE const gchar GINTPTR_MODIFIER_[] = G_GINTPTR_MODIFIER;

GI_MODULE_INLINE const gchar GSIZE_FORMAT_[] = G_GSIZE_FORMAT;

GI_MODULE_INLINE const gchar GSIZE_MODIFIER_[] = G_GSIZE_MODIFIER;

GI_MODULE_INLINE const gchar GSSIZE_FORMAT_[] = G_GSSIZE_FORMAT;

GI_MODULE_INLINE const gchar GSSIZE_MODIFIER_[] = G_GSSIZE_MODIFIER;

GI_MODULE_INLINE const gchar GUINT16_FORMAT_[] = G_GUINT16_FORMAT;

GI_MODULE_INLINE const gchar GUINT32_FORMAT_[] = G_GUINT32_FORMAT;

GI_MODULE_INLINE const gchar GUINT64_FORMAT_[] = G_GUINT64_FORMAT;

GI_MODULE_INLINE const gchar GUINTPTR_FORMAT_[] = G_GUINTPTR_FORMAT;

GI_MODULE_INLINE const gint HAVE_GINT64_ = G_HAVE_GINT64;

GI_MODULE_INLINE const gint HAVE_GNUC_VARARGS_ = G_HAVE_GNUC_VARARGS;

GI_MODULE_INLINE const gint HAVE_GNUC_VISIBILITY_ = G_HAVE_GNUC_VISIBILITY;

GI_MODULE_INLINE const gint HAVE_GROWING_STACK_ = G_HAVE_GROWING_STACK;

GI_MODULE_INLINE const gint HAVE_ISO_VARARGS_ = G_HAVE_ISO_VARARGS;

GI_MODULE_INLINE const gint HOOK_FLAG_USER_SHIFT_ = G_HOOK_FLAG_USER_SHIFT;

GI_MODULE_INLINE const gint IEEE754_DOUBLE_BIAS_ = G_IEEE754_DOUBLE_BIAS;

GI_MODULE_INLINE const gint IEEE754_FLOAT_BIAS_ = G_IEEE754_FLOAT_BIAS;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_GROUP_[] = G_KEY_FILE_DESKTOP_GROUP;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_ACTIONS_[] = G_KEY_FILE_DESKTOP_KEY_ACTIONS;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_CATEGORIES_[] = G_KEY_FILE_DESKTOP_KEY_CATEGORIES;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_COMMENT_[] = G_KEY_FILE_DESKTOP_KEY_COMMENT;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE_[] = G_KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_EXEC_[] = G_KEY_FILE_DESKTOP_KEY_EXEC;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_GENERIC_NAME_[] = G_KEY_FILE_DESKTOP_KEY_GENERIC_NAME;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_HIDDEN_[] = G_KEY_FILE_DESKTOP_KEY_HIDDEN;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_ICON_[] = G_KEY_FILE_DESKTOP_KEY_ICON;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_MIME_TYPE_[] = G_KEY_FILE_DESKTOP_KEY_MIME_TYPE;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_NAME_[] = G_KEY_FILE_DESKTOP_KEY_NAME;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN_[] = G_KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_NO_DISPLAY_[] = G_KEY_FILE_DESKTOP_KEY_NO_DISPLAY;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN_[] = G_KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_PATH_[] = G_KEY_FILE_DESKTOP_KEY_PATH;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY_[] = G_KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS_[] = G_KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_TERMINAL_[] = G_KEY_FILE_DESKTOP_KEY_TERMINAL;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_TRY_EXEC_[] = G_KEY_FILE_DESKTOP_KEY_TRY_EXEC;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_TYPE_[] = G_KEY_FILE_DESKTOP_KEY_TYPE;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_URL_[] = G_KEY_FILE_DESKTOP_KEY_URL;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_KEY_VERSION_[] = G_KEY_FILE_DESKTOP_KEY_VERSION;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_TYPE_APPLICATION_[] = G_KEY_FILE_DESKTOP_TYPE_APPLICATION;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_TYPE_DIRECTORY_[] = G_KEY_FILE_DESKTOP_TYPE_DIRECTORY;

GI_MODULE_INLINE const gchar KEY_FILE_DESKTOP_TYPE_LINK_[] = G_KEY_FILE_DESKTOP_TYPE_LINK;

GI_MODULE_INLINE const gint LITTLE_ENDIAN_ = G_LITTLE_ENDIAN;

GI_MODULE_INLINE const gdouble LN10_ = G_LN10;

GI_MODULE_INLINE const gdouble LN2_ = G_LN2;

GI_MODULE_INLINE const gdouble LOG_2_BASE_10_ = G_LOG_2_BASE_10;

GI_MODULE_INLINE const gint LOG_FATAL_MASK_ = G_LOG_FATAL_MASK;

GI_MODULE_INLINE const gint LOG_LEVEL_USER_SHIFT_ = G_LOG_LEVEL_USER_SHIFT;

GI_MODULE_INLINE const gint MAJOR_VERSION_ = GLIB_MAJOR_VERSION;

GI_MODULE_INLINE const gint16 MAXINT16_ = G_MAXINT16;

GI_MODULE_INLINE const gint32 MAXINT32_ = G_MAXINT32;

GI_MODULE_INLINE const gint64 MAXINT64_ = G_MAXINT64;

GI_MODULE_INLINE const gint8 MAXINT8_ = G_MAXINT8;

GI_MODULE_INLINE const guint16 MAXUINT16_ = G_MAXUINT16;

GI_MODULE_INLINE const guint32 MAXUINT32_ = G_MAXUINT32;

GI_MODULE_INLINE const guint64 MAXUINT64_ = G_MAXUINT64;

GI_MODULE_INLINE const guint8 MAXUINT8_ = G_MAXUINT8;

GI_MODULE_INLINE const gint MICRO_VERSION_ = GLIB_MICRO_VERSION;

GI_MODULE_INLINE const gint16 MININT16_ = G_MININT16;

GI_MODULE_INLINE const gint32 MININT32_ = G_MININT32;

GI_MODULE_INLINE const gint64 MININT64_ = G_MININT64;

GI_MODULE_INLINE const gint8 MININT8_ = G_MININT8;

GI_MODULE_INLINE const gint MINOR_VERSION_ = GLIB_MINOR_VERSION;

GI_MODULE_INLINE const gchar MODULE_SUFFIX_[] = G_MODULE_SUFFIX;

GI_MODULE_INLINE const guint64 NSEC_PER_SEC_ = G_NSEC_PER_SEC;

GI_MODULE_INLINE const gchar OPTION_REMAINING_[] = G_OPTION_REMAINING;

GI_MODULE_INLINE const gint PDP_ENDIAN_ = G_PDP_ENDIAN;

GI_MODULE_INLINE const gdouble PI_ = G_PI;

GI_MODULE_INLINE const gchar PID_FORMAT_[] = G_PID_FORMAT;

GI_MODULE_INLINE const gdouble PI_2_ = G_PI_2;

GI_MODULE_INLINE const gdouble PI_4_ = G_PI_4;

GI_MODULE_INLINE const gchar POLLFD_FORMAT_[] = G_POLLFD_FORMAT;

GI_MODULE_INLINE const gint PRIORITY_DEFAULT_ = G_PRIORITY_DEFAULT;

GI_MODULE_INLINE const gint PRIORITY_DEFAULT_IDLE_ = G_PRIORITY_DEFAULT_IDLE;

GI_MODULE_INLINE const gint PRIORITY_HIGH_ = G_PRIORITY_HIGH;

GI_MODULE_INLINE const gint PRIORITY_HIGH_IDLE_ = G_PRIORITY_HIGH_IDLE;

GI_MODULE_INLINE const gint PRIORITY_LOW_ = G_PRIORITY_LOW;

GI_MODULE_INLINE const gint REF_COUNT_INIT_ = G_REF_COUNT_INIT;

GI_MODULE_INLINE const gint SEARCHPATH_SEPARATOR_ = G_SEARCHPATH_SEPARATOR;

GI_MODULE_INLINE const gchar SEARCHPATH_SEPARATOR_S_[] = G_SEARCHPATH_SEPARATOR_S;

GI_MODULE_INLINE const gint SIZEOF_LONG_ = GLIB_SIZEOF_LONG;

GI_MODULE_INLINE const gint SIZEOF_SIZE_T_ = GLIB_SIZEOF_SIZE_T;

GI_MODULE_INLINE const gint SIZEOF_SSIZE_T_ = GLIB_SIZEOF_SSIZE_T;

GI_MODULE_INLINE const gint SIZEOF_VOID_P_ = GLIB_SIZEOF_VOID_P;

GI_MODULE_INLINE const gboolean SOURCE_CONTINUE_ = G_SOURCE_CONTINUE;

GI_MODULE_INLINE const gboolean SOURCE_REMOVE_ = G_SOURCE_REMOVE;

GI_MODULE_INLINE const gdouble SQRT2_ = G_SQRT2;

GI_MODULE_INLINE const gchar STR_DELIMITERS_[] = G_STR_DELIMITERS;

GI_MODULE_INLINE const gint SYSDEF_AF_INET_ = GLIB_SYSDEF_AF_INET;

GI_MODULE_INLINE const gint SYSDEF_AF_INET6_ = GLIB_SYSDEF_AF_INET6;

GI_MODULE_INLINE const gint SYSDEF_AF_UNIX_ = GLIB_SYSDEF_AF_UNIX;

GI_MODULE_INLINE const gint SYSDEF_MSG_DONTROUTE_ = GLIB_SYSDEF_MSG_DONTROUTE;

GI_MODULE_INLINE const gint SYSDEF_MSG_OOB_ = GLIB_SYSDEF_MSG_OOB;

GI_MODULE_INLINE const gint SYSDEF_MSG_PEEK_ = GLIB_SYSDEF_MSG_PEEK;

GI_MODULE_INLINE const gchar TEST_OPTION_ISOLATE_DIRS_[] = G_TEST_OPTION_ISOLATE_DIRS;

GI_MODULE_INLINE const gchar TEST_OPTION_NONFATAL_ASSERTIONS_[] = G_TEST_OPTION_NONFATAL_ASSERTIONS;

GI_MODULE_INLINE const gchar TEST_OPTION_NO_PRGNAME_[] = G_TEST_OPTION_NO_PRGNAME;

GI_MODULE_INLINE const gint64 TIME_SPAN_DAY_ = G_TIME_SPAN_DAY;

GI_MODULE_INLINE const gint64 TIME_SPAN_HOUR_ = G_TIME_SPAN_HOUR;

GI_MODULE_INLINE const gint64 TIME_SPAN_MILLISECOND_ = G_TIME_SPAN_MILLISECOND;

GI_MODULE_INLINE const gint64 TIME_SPAN_MINUTE_ = G_TIME_SPAN_MINUTE;

GI_MODULE_INLINE const gint64 TIME_SPAN_SECOND_ = G_TIME_SPAN_SECOND;

GI_MODULE_INLINE const gint UNICHAR_MAX_DECOMPOSITION_LENGTH_ = G_UNICHAR_MAX_DECOMPOSITION_LENGTH;

GI_MODULE_INLINE const gchar URI_RESERVED_CHARS_GENERIC_DELIMITERS_[] = G_URI_RESERVED_CHARS_GENERIC_DELIMITERS;

GI_MODULE_INLINE const gchar URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS_[] = G_URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS;

GI_MODULE_INLINE const gint USEC_PER_SEC_ = G_USEC_PER_SEC;

GI_MODULE_INLINE const gint VA_COPY_AS_ARRAY_ = G_VA_COPY_AS_ARRAY;

GI_MODULE_INLINE const gint VERSION_MIN_REQUIRED_ = GLIB_VERSION_MIN_REQUIRED;

} // namespace GLib

} // namespace repository

} // namespace gi

#endif
