// AUTO-GENERATED

#ifndef _GI_GIO__CONSTANTS_HPP_
#define _GI_GIO__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Gio {

GI_MODULE_INLINE const gboolean DBUS_METHOD_INVOCATION_HANDLED_ = G_DBUS_METHOD_INVOCATION_HANDLED;

GI_MODULE_INLINE const gboolean DBUS_METHOD_INVOCATION_UNHANDLED_ = G_DBUS_METHOD_INVOCATION_UNHANDLED;

GI_MODULE_INLINE const gchar DEBUG_CONTROLLER_EXTENSION_POINT_NAME_[] = G_DEBUG_CONTROLLER_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar DRIVE_IDENTIFIER_KIND_UNIX_DEVICE_[] = G_DRIVE_IDENTIFIER_KIND_UNIX_DEVICE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_DELETE_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_DELETE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_EXECUTE_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_EXECUTE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_READ_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_READ;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_RENAME_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_RENAME;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_TRASH_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_TRASH;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ACCESS_CAN_WRITE_[] = G_FILE_ATTRIBUTE_ACCESS_CAN_WRITE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_DOS_IS_ARCHIVE_[] = G_FILE_ATTRIBUTE_DOS_IS_ARCHIVE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_DOS_IS_MOUNTPOINT_[] = G_FILE_ATTRIBUTE_DOS_IS_MOUNTPOINT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_DOS_IS_SYSTEM_[] = G_FILE_ATTRIBUTE_DOS_IS_SYSTEM;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_DOS_REPARSE_POINT_TAG_[] = G_FILE_ATTRIBUTE_DOS_REPARSE_POINT_TAG;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ETAG_VALUE_[] = G_FILE_ATTRIBUTE_ETAG_VALUE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_FREE_[] = G_FILE_ATTRIBUTE_FILESYSTEM_FREE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_READONLY_[] = G_FILE_ATTRIBUTE_FILESYSTEM_READONLY;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_REMOTE_[] = G_FILE_ATTRIBUTE_FILESYSTEM_REMOTE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_SIZE_[] = G_FILE_ATTRIBUTE_FILESYSTEM_SIZE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_TYPE_[] = G_FILE_ATTRIBUTE_FILESYSTEM_TYPE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_USED_[] = G_FILE_ATTRIBUTE_FILESYSTEM_USED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW_[] = G_FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_GVFS_BACKEND_[] = G_FILE_ATTRIBUTE_GVFS_BACKEND;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ID_FILE_[] = G_FILE_ATTRIBUTE_ID_FILE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_ID_FILESYSTEM_[] = G_FILE_ATTRIBUTE_ID_FILESYSTEM;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_POLL_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_POLL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_START_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_START;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_START_DEGRADED_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_START_DEGRADED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_STOP_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_STOP;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT_[] = G_FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_HAL_UDI_[] = G_FILE_ATTRIBUTE_MOUNTABLE_HAL_UDI;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_IS_MEDIA_CHECK_AUTOMATIC_[] = G_FILE_ATTRIBUTE_MOUNTABLE_IS_MEDIA_CHECK_AUTOMATIC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_START_STOP_TYPE_[] = G_FILE_ATTRIBUTE_MOUNTABLE_START_STOP_TYPE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_[] = G_FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_FILE_[] = G_FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_FILE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_OWNER_GROUP_[] = G_FILE_ATTRIBUTE_OWNER_GROUP;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_OWNER_USER_[] = G_FILE_ATTRIBUTE_OWNER_USER;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_OWNER_USER_REAL_[] = G_FILE_ATTRIBUTE_OWNER_USER_REAL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_PREVIEW_ICON_[] = G_FILE_ATTRIBUTE_PREVIEW_ICON;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_RECENT_MODIFIED_[] = G_FILE_ATTRIBUTE_RECENT_MODIFIED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_SELINUX_CONTEXT_[] = G_FILE_ATTRIBUTE_SELINUX_CONTEXT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_ALLOCATED_SIZE_[] = G_FILE_ATTRIBUTE_STANDARD_ALLOCATED_SIZE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE_[] = G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_COPY_NAME_[] = G_FILE_ATTRIBUTE_STANDARD_COPY_NAME;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_DESCRIPTION_[] = G_FILE_ATTRIBUTE_STANDARD_DESCRIPTION;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME_[] = G_FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_EDIT_NAME_[] = G_FILE_ATTRIBUTE_STANDARD_EDIT_NAME;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_FAST_CONTENT_TYPE_[] = G_FILE_ATTRIBUTE_STANDARD_FAST_CONTENT_TYPE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_ICON_[] = G_FILE_ATTRIBUTE_STANDARD_ICON;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_IS_BACKUP_[] = G_FILE_ATTRIBUTE_STANDARD_IS_BACKUP;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_IS_HIDDEN_[] = G_FILE_ATTRIBUTE_STANDARD_IS_HIDDEN;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_IS_SYMLINK_[] = G_FILE_ATTRIBUTE_STANDARD_IS_SYMLINK;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_IS_VIRTUAL_[] = G_FILE_ATTRIBUTE_STANDARD_IS_VIRTUAL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_IS_VOLATILE_[] = G_FILE_ATTRIBUTE_STANDARD_IS_VOLATILE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_NAME_[] = G_FILE_ATTRIBUTE_STANDARD_NAME;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_SIZE_[] = G_FILE_ATTRIBUTE_STANDARD_SIZE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_SORT_ORDER_[] = G_FILE_ATTRIBUTE_STANDARD_SORT_ORDER;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_SYMBOLIC_ICON_[] = G_FILE_ATTRIBUTE_STANDARD_SYMBOLIC_ICON;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_SYMLINK_TARGET_[] = G_FILE_ATTRIBUTE_STANDARD_SYMLINK_TARGET;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_TARGET_URI_[] = G_FILE_ATTRIBUTE_STANDARD_TARGET_URI;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_STANDARD_TYPE_[] = G_FILE_ATTRIBUTE_STANDARD_TYPE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAILING_FAILED_[] = G_FILE_ATTRIBUTE_THUMBNAILING_FAILED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAILING_FAILED_LARGE_[] = G_FILE_ATTRIBUTE_THUMBNAILING_FAILED_LARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAILING_FAILED_NORMAL_[] = G_FILE_ATTRIBUTE_THUMBNAILING_FAILED_NORMAL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAILING_FAILED_XLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAILING_FAILED_XLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAILING_FAILED_XXLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAILING_FAILED_XXLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_[] = G_FILE_ATTRIBUTE_THUMBNAIL_IS_VALID;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_LARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_LARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_NORMAL_[] = G_FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_NORMAL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_XLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_XLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_XXLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_IS_VALID_XXLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_PATH_[] = G_FILE_ATTRIBUTE_THUMBNAIL_PATH;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_PATH_LARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_PATH_LARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_PATH_NORMAL_[] = G_FILE_ATTRIBUTE_THUMBNAIL_PATH_NORMAL;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_PATH_XLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_PATH_XLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_THUMBNAIL_PATH_XXLARGE_[] = G_FILE_ATTRIBUTE_THUMBNAIL_PATH_XXLARGE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_ACCESS_[] = G_FILE_ATTRIBUTE_TIME_ACCESS;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_ACCESS_NSEC_[] = G_FILE_ATTRIBUTE_TIME_ACCESS_NSEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_ACCESS_USEC_[] = G_FILE_ATTRIBUTE_TIME_ACCESS_USEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CHANGED_[] = G_FILE_ATTRIBUTE_TIME_CHANGED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CHANGED_NSEC_[] = G_FILE_ATTRIBUTE_TIME_CHANGED_NSEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CHANGED_USEC_[] = G_FILE_ATTRIBUTE_TIME_CHANGED_USEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CREATED_[] = G_FILE_ATTRIBUTE_TIME_CREATED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CREATED_NSEC_[] = G_FILE_ATTRIBUTE_TIME_CREATED_NSEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_CREATED_USEC_[] = G_FILE_ATTRIBUTE_TIME_CREATED_USEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_MODIFIED_[] = G_FILE_ATTRIBUTE_TIME_MODIFIED;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_MODIFIED_NSEC_[] = G_FILE_ATTRIBUTE_TIME_MODIFIED_NSEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TIME_MODIFIED_USEC_[] = G_FILE_ATTRIBUTE_TIME_MODIFIED_USEC;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TRASH_DELETION_DATE_[] = G_FILE_ATTRIBUTE_TRASH_DELETION_DATE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TRASH_ITEM_COUNT_[] = G_FILE_ATTRIBUTE_TRASH_ITEM_COUNT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_TRASH_ORIG_PATH_[] = G_FILE_ATTRIBUTE_TRASH_ORIG_PATH;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_BLOCKS_[] = G_FILE_ATTRIBUTE_UNIX_BLOCKS;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_BLOCK_SIZE_[] = G_FILE_ATTRIBUTE_UNIX_BLOCK_SIZE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_DEVICE_[] = G_FILE_ATTRIBUTE_UNIX_DEVICE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_GID_[] = G_FILE_ATTRIBUTE_UNIX_GID;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_INODE_[] = G_FILE_ATTRIBUTE_UNIX_INODE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT_[] = G_FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_MODE_[] = G_FILE_ATTRIBUTE_UNIX_MODE;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_NLINK_[] = G_FILE_ATTRIBUTE_UNIX_NLINK;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_RDEV_[] = G_FILE_ATTRIBUTE_UNIX_RDEV;

GI_MODULE_INLINE const gchar FILE_ATTRIBUTE_UNIX_UID_[] = G_FILE_ATTRIBUTE_UNIX_UID;

GI_MODULE_INLINE const gchar MEMORY_MONITOR_EXTENSION_POINT_NAME_[] = G_MEMORY_MONITOR_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar MENU_ATTRIBUTE_ACTION_[] = G_MENU_ATTRIBUTE_ACTION;

GI_MODULE_INLINE const gchar MENU_ATTRIBUTE_ACTION_NAMESPACE_[] = G_MENU_ATTRIBUTE_ACTION_NAMESPACE;

GI_MODULE_INLINE const gchar MENU_ATTRIBUTE_ICON_[] = G_MENU_ATTRIBUTE_ICON;

GI_MODULE_INLINE const gchar MENU_ATTRIBUTE_LABEL_[] = G_MENU_ATTRIBUTE_LABEL;

GI_MODULE_INLINE const gchar MENU_ATTRIBUTE_TARGET_[] = G_MENU_ATTRIBUTE_TARGET;

GI_MODULE_INLINE const gint MENU_EXPORTER_MAX_SECTION_SIZE_ = G_MENU_EXPORTER_MAX_SECTION_SIZE;

GI_MODULE_INLINE const gchar MENU_LINK_SECTION_[] = G_MENU_LINK_SECTION;

GI_MODULE_INLINE const gchar MENU_LINK_SUBMENU_[] = G_MENU_LINK_SUBMENU;

GI_MODULE_INLINE const gchar NATIVE_VOLUME_MONITOR_EXTENSION_POINT_NAME_[] = G_NATIVE_VOLUME_MONITOR_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar NETWORK_MONITOR_EXTENSION_POINT_NAME_[] = G_NETWORK_MONITOR_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar POWER_PROFILE_MONITOR_EXTENSION_POINT_NAME_[] = G_POWER_PROFILE_MONITOR_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar PROXY_EXTENSION_POINT_NAME_[] = G_PROXY_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar PROXY_RESOLVER_EXTENSION_POINT_NAME_[] = G_PROXY_RESOLVER_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar SETTINGS_BACKEND_EXTENSION_POINT_NAME_[] = G_SETTINGS_BACKEND_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar TLS_BACKEND_EXTENSION_POINT_NAME_[] = G_TLS_BACKEND_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar TLS_DATABASE_PURPOSE_AUTHENTICATE_CLIENT_[] = G_TLS_DATABASE_PURPOSE_AUTHENTICATE_CLIENT;

GI_MODULE_INLINE const gchar TLS_DATABASE_PURPOSE_AUTHENTICATE_SERVER_[] = G_TLS_DATABASE_PURPOSE_AUTHENTICATE_SERVER;

GI_MODULE_INLINE const gchar VFS_EXTENSION_POINT_NAME_[] = G_VFS_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gchar VOLUME_IDENTIFIER_KIND_CLASS_[] = G_VOLUME_IDENTIFIER_KIND_CLASS;

GI_MODULE_INLINE const gchar VOLUME_IDENTIFIER_KIND_LABEL_[] = G_VOLUME_IDENTIFIER_KIND_LABEL;

GI_MODULE_INLINE const gchar VOLUME_IDENTIFIER_KIND_NFS_MOUNT_[] = G_VOLUME_IDENTIFIER_KIND_NFS_MOUNT;

GI_MODULE_INLINE const gchar VOLUME_IDENTIFIER_KIND_UNIX_DEVICE_[] = G_VOLUME_IDENTIFIER_KIND_UNIX_DEVICE;

GI_MODULE_INLINE const gchar VOLUME_IDENTIFIER_KIND_UUID_[] = G_VOLUME_IDENTIFIER_KIND_UUID;

GI_MODULE_INLINE const gchar VOLUME_MONITOR_EXTENSION_POINT_NAME_[] = G_VOLUME_MONITOR_EXTENSION_POINT_NAME;

} // namespace Gio

} // namespace repository

} // namespace gi

#endif
