// AUTO-GENERATED

#ifndef _GI_GTK__CONSTANTS_HPP_
#define _GI_GTK__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Gtk {

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_BACKGROUND_[] = GTK_ACCESSIBLE_ATTRIBUTE_BACKGROUND;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_FAMILY_[] = GTK_ACCESSIBLE_ATTRIBUTE_FAMILY;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_FOREGROUND_[] = GTK_ACCESSIBLE_ATTRIBUTE_FOREGROUND;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_OVERLINE_[] = GTK_ACCESSIBLE_ATTRIBUTE_OVERLINE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_OVERLINE_NONE_[] = GTK_ACCESSIBLE_ATTRIBUTE_OVERLINE_NONE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_OVERLINE_SINGLE_[] = GTK_ACCESSIBLE_ATTRIBUTE_OVERLINE_SINGLE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_SIZE_[] = GTK_ACCESSIBLE_ATTRIBUTE_SIZE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_CONDENSED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_CONDENSED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_EXPANDED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_EXPANDED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_CONDENSED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_CONDENSED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_EXPANDED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_EXPANDED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_NORMAL_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_NORMAL;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_CONDENSED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_CONDENSED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_EXPANDED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_EXPANDED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_CONDENSED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_CONDENSED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_EXPANDED_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_EXPANDED;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STRIKETHROUGH_[] = GTK_ACCESSIBLE_ATTRIBUTE_STRIKETHROUGH;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STYLE_[] = GTK_ACCESSIBLE_ATTRIBUTE_STYLE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STYLE_ITALIC_[] = GTK_ACCESSIBLE_ATTRIBUTE_STYLE_ITALIC;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STYLE_NORMAL_[] = GTK_ACCESSIBLE_ATTRIBUTE_STYLE_NORMAL;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_STYLE_OBLIQUE_[] = GTK_ACCESSIBLE_ATTRIBUTE_STYLE_OBLIQUE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_UNDERLINE_[] = GTK_ACCESSIBLE_ATTRIBUTE_UNDERLINE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_UNDERLINE_DOUBLE_[] = GTK_ACCESSIBLE_ATTRIBUTE_UNDERLINE_DOUBLE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_UNDERLINE_ERROR_[] = GTK_ACCESSIBLE_ATTRIBUTE_UNDERLINE_ERROR;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_UNDERLINE_NONE_[] = GTK_ACCESSIBLE_ATTRIBUTE_UNDERLINE_NONE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_UNDERLINE_SINGLE_[] = GTK_ACCESSIBLE_ATTRIBUTE_UNDERLINE_SINGLE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_PETITE_CAPS_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_PETITE_CAPS;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_SMALL_CAPS_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_SMALL_CAPS;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_PETITE_CAPS_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_PETITE_CAPS;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_SMALL_CAPS_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_SMALL_CAPS;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_TITLE_CAPS_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_TITLE_CAPS;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_VARIANT_UNICASE_[] = GTK_ACCESSIBLE_ATTRIBUTE_VARIANT_UNICASE;

GI_MODULE_INLINE const gchar ACCESSIBLE_ATTRIBUTE_WEIGHT_[] = GTK_ACCESSIBLE_ATTRIBUTE_WEIGHT;

GI_MODULE_INLINE const gint ACCESSIBLE_VALUE_UNDEFINED_ = GTK_ACCESSIBLE_VALUE_UNDEFINED;

GI_MODULE_INLINE const gint BINARY_AGE_ = GTK_BINARY_AGE;

GI_MODULE_INLINE const gint INPUT_ERROR_ = GTK_INPUT_ERROR;

GI_MODULE_INLINE const gint INTERFACE_AGE_ = GTK_INTERFACE_AGE;

GI_MODULE_INLINE const guint INVALID_LIST_POSITION_ = GTK_INVALID_LIST_POSITION;

GI_MODULE_INLINE const gchar LEVEL_BAR_OFFSET_FULL_[] = GTK_LEVEL_BAR_OFFSET_FULL;

GI_MODULE_INLINE const gchar LEVEL_BAR_OFFSET_HIGH_[] = GTK_LEVEL_BAR_OFFSET_HIGH;

GI_MODULE_INLINE const gchar LEVEL_BAR_OFFSET_LOW_[] = GTK_LEVEL_BAR_OFFSET_LOW;

GI_MODULE_INLINE const gint MAJOR_VERSION_ = GTK_MAJOR_VERSION;

GI_MODULE_INLINE const gint MAX_COMPOSE_LEN_ = GTK_MAX_COMPOSE_LEN;

GI_MODULE_INLINE const gchar MEDIA_FILE_EXTENSION_POINT_NAME_[] = GTK_MEDIA_FILE_EXTENSION_POINT_NAME;

GI_MODULE_INLINE const gint MICRO_VERSION_ = GTK_MICRO_VERSION;

GI_MODULE_INLINE const gint MINOR_VERSION_ = GTK_MINOR_VERSION;

GI_MODULE_INLINE const gchar PAPER_NAME_A3_[] = GTK_PAPER_NAME_A3;

GI_MODULE_INLINE const gchar PAPER_NAME_A4_[] = GTK_PAPER_NAME_A4;

GI_MODULE_INLINE const gchar PAPER_NAME_A5_[] = GTK_PAPER_NAME_A5;

GI_MODULE_INLINE const gchar PAPER_NAME_B5_[] = GTK_PAPER_NAME_B5;

GI_MODULE_INLINE const gchar PAPER_NAME_EXECUTIVE_[] = GTK_PAPER_NAME_EXECUTIVE;

GI_MODULE_INLINE const gchar PAPER_NAME_LEGAL_[] = GTK_PAPER_NAME_LEGAL;

GI_MODULE_INLINE const gchar PAPER_NAME_LETTER_[] = GTK_PAPER_NAME_LETTER;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_COLLATE_[] = GTK_PRINT_SETTINGS_COLLATE;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_DEFAULT_SOURCE_[] = GTK_PRINT_SETTINGS_DEFAULT_SOURCE;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_DITHER_[] = GTK_PRINT_SETTINGS_DITHER;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_DUPLEX_[] = GTK_PRINT_SETTINGS_DUPLEX;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_FINISHINGS_[] = GTK_PRINT_SETTINGS_FINISHINGS;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_MEDIA_TYPE_[] = GTK_PRINT_SETTINGS_MEDIA_TYPE;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_NUMBER_UP_[] = GTK_PRINT_SETTINGS_NUMBER_UP;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_NUMBER_UP_LAYOUT_[] = GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_N_COPIES_[] = GTK_PRINT_SETTINGS_N_COPIES;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_ORIENTATION_[] = GTK_PRINT_SETTINGS_ORIENTATION;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_OUTPUT_BASENAME_[] = GTK_PRINT_SETTINGS_OUTPUT_BASENAME;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_OUTPUT_BIN_[] = GTK_PRINT_SETTINGS_OUTPUT_BIN;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_OUTPUT_DIR_[] = GTK_PRINT_SETTINGS_OUTPUT_DIR;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_OUTPUT_FILE_FORMAT_[] = GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_OUTPUT_URI_[] = GTK_PRINT_SETTINGS_OUTPUT_URI;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PAGE_RANGES_[] = GTK_PRINT_SETTINGS_PAGE_RANGES;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PAGE_SET_[] = GTK_PRINT_SETTINGS_PAGE_SET;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PAPER_FORMAT_[] = GTK_PRINT_SETTINGS_PAPER_FORMAT;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PAPER_HEIGHT_[] = GTK_PRINT_SETTINGS_PAPER_HEIGHT;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PAPER_WIDTH_[] = GTK_PRINT_SETTINGS_PAPER_WIDTH;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PRINTER_[] = GTK_PRINT_SETTINGS_PRINTER;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PRINTER_LPI_[] = GTK_PRINT_SETTINGS_PRINTER_LPI;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_PRINT_PAGES_[] = GTK_PRINT_SETTINGS_PRINT_PAGES;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_QUALITY_[] = GTK_PRINT_SETTINGS_QUALITY;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_RESOLUTION_[] = GTK_PRINT_SETTINGS_RESOLUTION;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_RESOLUTION_X_[] = GTK_PRINT_SETTINGS_RESOLUTION_X;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_RESOLUTION_Y_[] = GTK_PRINT_SETTINGS_RESOLUTION_Y;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_REVERSE_[] = GTK_PRINT_SETTINGS_REVERSE;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_SCALE_[] = GTK_PRINT_SETTINGS_SCALE;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_USE_COLOR_[] = GTK_PRINT_SETTINGS_USE_COLOR;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_WIN32_DRIVER_EXTRA_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA;

GI_MODULE_INLINE const gchar PRINT_SETTINGS_WIN32_DRIVER_VERSION_[] = GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION;

GI_MODULE_INLINE const gint PRIORITY_RESIZE_ = GTK_PRIORITY_RESIZE;

GI_MODULE_INLINE const gint STYLE_PROVIDER_PRIORITY_APPLICATION_ = GTK_STYLE_PROVIDER_PRIORITY_APPLICATION;

GI_MODULE_INLINE const gint STYLE_PROVIDER_PRIORITY_FALLBACK_ = GTK_STYLE_PROVIDER_PRIORITY_FALLBACK;

GI_MODULE_INLINE const gint STYLE_PROVIDER_PRIORITY_SETTINGS_ = GTK_STYLE_PROVIDER_PRIORITY_SETTINGS;

GI_MODULE_INLINE const gint STYLE_PROVIDER_PRIORITY_THEME_ = GTK_STYLE_PROVIDER_PRIORITY_THEME;

GI_MODULE_INLINE const gint STYLE_PROVIDER_PRIORITY_USER_ = GTK_STYLE_PROVIDER_PRIORITY_USER;

GI_MODULE_INLINE const gint SVG_DEFAULT_FEATURES_ = GTK_SVG_DEFAULT_FEATURES;

GI_MODULE_INLINE const gint TEXT_VIEW_PRIORITY_VALIDATE_ = GTK_TEXT_VIEW_PRIORITY_VALIDATE;

GI_MODULE_INLINE const gint TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID;

GI_MODULE_INLINE const gint TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID_ = GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID;

} // namespace Gtk

} // namespace repository

} // namespace gi

#endif
