// AUTO-GENERATED

#ifndef _GI_PANGO__CONSTANTS_HPP_
#define _GI_PANGO__CONSTANTS_HPP_

namespace gi {

namespace repository {

namespace Pango {

GI_MODULE_INLINE const gint ANALYSIS_FLAG_CENTERED_BASELINE_ = PANGO_ANALYSIS_FLAG_CENTERED_BASELINE;

GI_MODULE_INLINE const gint ANALYSIS_FLAG_IS_ELLIPSIS_ = PANGO_ANALYSIS_FLAG_IS_ELLIPSIS;

GI_MODULE_INLINE const gint ANALYSIS_FLAG_NEED_HYPHEN_ = PANGO_ANALYSIS_FLAG_NEED_HYPHEN;

GI_MODULE_INLINE const guint ATTR_INDEX_FROM_TEXT_BEGINNING_ = PANGO_ATTR_INDEX_FROM_TEXT_BEGINNING;

GI_MODULE_INLINE const guint ATTR_INDEX_TO_TEXT_END_ = PANGO_ATTR_INDEX_TO_TEXT_END;

GI_MODULE_INLINE const PangoGlyph GLYPH_EMPTY_ = PANGO_GLYPH_EMPTY;

GI_MODULE_INLINE const PangoGlyph GLYPH_INVALID_INPUT_ = PANGO_GLYPH_INVALID_INPUT;

GI_MODULE_INLINE const PangoGlyph GLYPH_UNKNOWN_FLAG_ = PANGO_GLYPH_UNKNOWN_FLAG;

GI_MODULE_INLINE const gint SCALE_ = PANGO_SCALE;

GI_MODULE_INLINE const gint VERSION_MAJOR_ = PANGO_VERSION_MAJOR;

GI_MODULE_INLINE const gint VERSION_MICRO_ = PANGO_VERSION_MICRO;

GI_MODULE_INLINE const gint VERSION_MINOR_ = PANGO_VERSION_MINOR;

GI_MODULE_INLINE const gchar VERSION_STRING_[] = PANGO_VERSION_STRING;

} // namespace Pango

} // namespace repository

} // namespace gi

#endif
